[
  ./arch-emu.nix
  ./bluetooth.nix
  ./common.nix
  ./fan2go.nix
  ./fileshelter.nix
  ./gaming.nix
  ./harpoond.nix
  ./opengl.nix
  ./primary-user.nix
  ./sops.nix
  ./sound.nix
  ./ssh.nix
  ./virtualisation.nix
  ./wireguard-client.nix
  ./wlr-screen-sharing.nix
]
