# Authors: NNB <nnbnh@protonmail.com>, Matthew Toohey <contact@mtoohey.com>

"attributes" = "yellow"
"comment" = { fg = "gray", modifiers = ["italic"] }
"constant.character.escape" = "light-cyan"
"constant.numeric" = "yellow"
"constant" = "yellow"
"constructor" = "light-blue"
"diff.delta" = "yellow"
"diff.minus" = "light-red"
"diff.plus" = "light-green"
"function" = "light-blue"
"keyword" = "light-magenta"
"label" = "light-magenta"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.heading" = "light-blue"
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.link.text" = "light-red"
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.list" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"
"namespace" = "light-magenta"
"special" = "light-blue"
"string"  = "light-green"
"type" = "light-yellow"
"variable" = "light-red"
"variable.other.member" = "light-green"

"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "light-yellow", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.gutter" = { bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.linenr" = { fg = "gray", bg = "black" }
"ui.linenr.selected" = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.menu" = { fg = "light-gray", bg = "black" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.popup" = { bg = "black" }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "white", bg = "black", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "blue", bg = "black" }
"ui.statusline.insert" = { fg = "green", bg = "black" }
"ui.statusline.select" = { fg = "yellow", bg = "black" }
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.indent-guide" = { fg = "gray", modifiers = ["dim"] }
"ui.window" = { bg = "black" }

"warning" = "yellow"
"error" = "light-red"
"info" = "light-blue"
"hint" = "gray"

"diagnostic" = { modifiers = ["underlined"] }
