name: "Check formatting and dead code"
on:
  push:
    branches: ["**"]
jobs:
  check_format_and_dead:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nix
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}
          flake_paths: .#devShells.x86_64-linux.ci
        # TODO: figure out a way to run nix flake check in here without it
        # failing because secrets.nix is encrypted
      - name: Check formatting and dead code
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop .#ci -ic make ci
