name: "Check formatting and dead code"
on:
  push:
    branches: ["**"]
jobs:
  check_format_and_dead:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install nixpkgs-fmt
        run: nix-env -i nixpkgs-fmt -f '<nixpkgs>'
      - name: Check formatting
        run: nixpkgs-fmt --check .
      - name: Install deadnix
        run: nix-env -i deadnix -f '<nixpkgs>'
      - name: Check dead code
        run: deadnix --fail $(find -name '*.nix' -not -name 'hardware-configuration.nix')
