name: "Check formatting"
on:
  push:
    branches: ["**"]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install nixpkgs-fmt
        run: nix-env -i nixpkgs-fmt -f '<nixpkgs>'
      #   run: nix-env -f https://github.com/nix-community/nixpkgs-fmt/archive/master.tar.gz -iA nixpkgs-fmt
      - name: Check formatting
        run: nixpkgs-fmt --check .
